[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.17.0"
  SENTRY_AUTH_TOKEN = "aasif123"  # Ensure this matches the token set in the Netlify UI

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@sentry/netlify-build-plugin"
