[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

  # Set the timeout for all functions
  [functions.constants]
  timeout = 30

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
