[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[functions."fetchJobs"]
  timeout = 120  # Increased timeout to 120 seconds

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
